_target_: src.tokenizer.multimodal_llama_tokenizer.MultimodalLlamaTokenizer.from_pretrained
pretrained_model_name_or_path: /mnt/petrelfs/share_data/likunchang/model/llm/internlm2-chat-20b
local_files_only: True
trust_remote_code: True
n_query: 96
v_query: 96