_target_: src.tokenizer.multimodal_llama_tokenizer.MultimodalLlamaTokenizer.from_pretrained
pretrained_model_name_or_path: /mnt/petrelfs/share/videointern/MLLM/internlm2_5_7b_1m
local_files_only: True
trust_remote_code: True
n_query: 96
v_query: 96