_target_: src.tokenizer.multimodal_llama_tokenizer.MultimodalLlamaTokenizer.from_pretrained
pretrained_model_name_or_path: /mnt/petrelfs/share/videointern/MLLM/Mistral-7B-Instruct-v0.3/
local_files_only: True
n_query: 480
v_query: 480