_target_: src.tokenizer.multimodal_llama_tokenizer.MultimodalLlamaTokenizer.from_pretrained
pretrained_model_name_or_path: /mnt/petrelfs/wangchenting/Mistral-7B-Instruct-v0.2
local_files_only: True
n_query: 96
v_query: 96